workspace = { members = ["aoc22"] }
[package]
name = "aoc22"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitmask = "0.5.0"
itertools = "0.11.0"
