[package]
name = "y23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "day1"
path = "src/1/day1.rs"

[[bin]]
name = "day2"
path = "src/2/day2.rs"

